spring:
  application:
    name: currency-conversion
  cloud:
    config:
      import-check:
        enabled: false
 
server:
  port: 8100
  
# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
service:
  url:
    currency-exchange: http://localhost:8000/
    
# EUREKA NAMING SERVER CONFIGURATION
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
# Log file
logging:
  file:
    name: logs.txt