spring:
  application:
    name: currency-conversion
  cloud:
    config:
      import-check:
        enabled: false
 
server:
  port: 8100
  
# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
service:
  url:
    currency-exchange: http://localhost:8000/